#pragma once
#include "CoreMinimal.h"
#include "ECareerRecordsInfo.generated.h"

UENUM(BlueprintType)
enum class ECareerRecordsInfo : uint8 {
    None,
    TotalMatche,
    Wins,
    Losses,
    Draws,
    BestMatchScore,
    AverageMatchScore,
    TotalSkillPoint,
    TotalCareerMoney,
    TimesRank_D,
    TimesRank_C,
    TimesRank_B,
    TimesRank_B_Plus,
    TimesRank_A,
    TimesRank_A_Plus,
    WorldChampionShips,
    WomensChampionShips,
    TagChampionShips,
    TntChampionShips,
    TbsChampionShips,
    FtwChampionShips,
    DynamiteWins,
    RampageWins,
    DarkWins,
    PpvWins,
    TotalWorkouts,
    TotalLightWorkouts,
    SuccessfulLightWorkouts,
    TotalStandardRoutines,
    SuccessfulStandardRoutines,
    TotalIntenseTraining,
    SuccessfulIntenseTraining,
    TotalDinings,
    TotalSightSeeing,
    TotalPressConferences,
    TotalMeetGreets,
    TotalTalkShow,
    TotalMinigamesPlay,
    TotalMinigamesWon,
    TotalHospital,
    TotalHospitalRecovery_A,
    TotalHospitalRecovery_B,
    TotalOtherMatches,
    OtherMatchWins,
    Injuries,
    UsedEnergyRecovery,
    UsedMotivationBoost,
    UsedInjuryTreatment,
    UsedSkillPointBooster,
    UsedMomentumBooster,
    UsedSpecialState,
    SnapshotsTaken,
};

