#pragma once
#include "CoreMinimal.h"
#include "ECareerChoicesSelectionResult.generated.h"

UENUM(BlueprintType)
enum class ECareerChoicesSelectionResult : uint8 {
    NONE,
    SELECTION_RESULT_01,
    SELECTION_RESULT_02,
    SELECTION_RESULT_03,
    SELECTION_RESULT_04,
    SELECTION_RESULT_05,
    SELECTION_RESULT_06,
    SELECTION_RESULT_07,
    SELECTION_RESULT_08,
    SELECTION_RESULT_09,
    SELECTION_RESULT_10,
    SELECTION_RESULT_11,
    SELECTION_RESULT_12,
    SELECTION_RESULT_13,
    SELECTION_RESULT_14,
    SELECTION_RESULT_15,
    SELECTION_RESULT_16,
    SELECTION_RESULT_17,
    SELECTION_RESULT_18,
    SELECTION_RESULT_19,
    SELECTION_RESULT_20,
    MAX,
};

