#pragma once
#include "CoreMinimal.h"
#include "ESSHeatSkillTarget.generated.h"

UENUM(BlueprintType)
enum class ESSHeatSkillTarget : uint8 {
    None,
    StandPunchWeak,
    StandPunchStrong,
    StandKickWeak,
    StandKickStrong,
    DashPunchWeak,
    DashPunchStrong,
    DashKickWeak,
    DashKickStrong,
    AirPunchWeak,
    AirPunchStrong,
    AirKickWeak,
    AirKickStrong,
    StandGrappleWeak,
    StandGrappleStrong,
    DashGrappleWeak,
    DashGrappleStrong,
    WeaponMeleeWeak,
    WeaponMeleeStrong,
    WeaponGun,
    WeaponThrow,
    Finisher,
    VehicleAttack,
    VehicleMoving,
    KO,
    Taunt,
    Destructible,
    All,
    WeakAll,
    StrongAll,
    StandPunchAll,
    StandKickAll,
    DashPunchAll,
    DashKickAll,
    PunchAll,
    KickAll,
    AirPunchAll,
    AirKickAll,
    AirStrikeAll,
    StandGrappleAll,
    DashGrappleAll,
    GrappleAll,
    WeaponMeleeAll,
    WeaponGunAll,
    WeaponThrowAll,
    WeaponAll,
    StrikeAll,
    HighFlyAll,
    Max,
    FilterStart = 0x1B,
    FilterEnd = 0x2F,
    CategoryNum = 0x1B,
};

