#pragma once
#include "CoreMinimal.h"
#include "ESSItemBoxType.generated.h"

UENUM(BlueprintType)
enum class ESSItemBoxType : uint8 {
    None,
    ItemBoxRound1,
    ItemBoxRound2,
    ItemBoxRound3,
    ItemBoxRound4,
    ItemBoxRound5,
    ItemBoxRound6,
    AbilityItemBox,
    TreasureBox1,
    TreasureBox2,
    TreasureBox3,
    TreasureBoxEpic1,
    TreasureBoxEpic2,
    TreasureBoxEpic3,
    TreasureBoxLegendary,
    CarrotTreasureBox,
    DefenseTeamTreasureBox,
    MultiLockedTeamTreasureBox,
    Vending,
    SlotMachineCommon,
    SlotMachineUnCommon,
    SlotMachineRare,
    SlotMachineEpic,
    SlotMachineLegendary,
    Max,
    ItemBoxBegin = ItemBoxRound1,
    ItemBoxEnd = AbilityItemBox,
    TreasureBoxBegin = TreasureBox1,
    TreasureBoxEnd = MultiLockedTeamTreasureBox,
    VendingBegin = Vending,
    VendingEnd = Vending,
    SlotMachineBegin = SlotMachineCommon,
    SlotMachineEnd = SlotMachineLegendary,
    Common = ItemBoxRound1,
    UnCommon = ItemBoxRound2,
    Rare = ItemBoxRound3,
    Epic = ItemBoxRound4,
    Legendary = ItemBoxRound5,
    TreasureCommon = TreasureBox1,
    TreasureUnCommon = TreasureBox2,
    TreasureRare = TreasureBox3,
    TreasureEpic = TreasureBoxEpic1,
    TreasureLegendary = TreasureBoxLegendary,
};

