#pragma once
#include "CoreMinimal.h"
#include "EBasicWrestlerIntParamType.generated.h"

UENUM(BlueprintType)
enum class EBasicWrestlerIntParamType : uint8 {
    WrestlerID,
    Gender,
    BodyType,
    BodyHeightType,
    BodyWeightType,
    Height,
    Weight,
    FaceType,
    SkinColorID,
    LeftEyeType,
    RightEyeType,
    BodyHeight,
    BodyMuscle,
    BodyFat,
    VoiceType,
    RingAnnounce1,
    RingAnnounce2,
    RingAnnounce3,
    BirthMonth,
    BirthDay,
    HomeTownID,
    FightStyle,
    FanReaction,
    FavoriteProps,
    Reserve024,
    Reserve025,
    Reserve026,
    Reserve027,
    Reserve028,
    Reserve029,
    Reserve030,
    Reserve031,
    Reserve032,
    Reserve033,
    Reserve034,
    Reserve035,
    Reserve036,
    Reserve037,
    Reserve038,
    Reserve039,
    Reserve040,
    Reserve041,
    Reserve042,
    Reserve043,
    Reserve044,
    Reserve045,
    Reserve046,
    Reserve047,
    Reserve048,
    Reserve049,
    Num,
};

