#pragma once
#include "CoreMinimal.h"
#include "EFinisher_Type.generated.h"

UENUM(BlueprintType)
enum class EFinisher_Type : uint8 {
    None,
    Front_Strike,
    Front_Chain,
    Rear_Strike,
    Rear_Chain,
    Front_Running,
    Rear_Running,
    Running_Counter,
    Stand_Diving,
    Down_Diving,
    Rope_SpringBoard_Stand,
    Rope_SpringBoard_Down,
    Corner_SpringBoard_Stand,
    Corner_SpringBoard_Down,
    Apron_SpringBoard_Stand,
    Apron_SpringBoard_Down,
    Down_FaceUp_Head,
    Down_FaceUp_Foot,
    Down_FaceUp_RHand,
    Down_FaceUp_LHand,
    Down_FaceDown_Head,
    Down_FaceDown_Foot,
    Down_FaceDown_RHand,
    Down_FaceDown_LHand,
    Front_SitDown,
    Rear_SitDown,
    Front_SitDown_Runnning,
    Rear_SitDown_Runnning,
    Front_CornerStandGroggy_Running,
    Rear_CornerStandGroggy_Running,
    Front_CornerChain,
    Rear_CornerChain,
    RopeGroggy_Running,
    MiddleRopeGroggy_Running,
    RopeChain_Stick_InRing,
    ApronStandAttack_Ring_To_Apron_Running,
    ApronChain_Ring_To_Apron_StickRing,
    Front_ApronChain_Apron_To_Ring_StickRing,
    Rear_ApronChain_Apron_To_Ring_StickRing,
    Diving_Intercept_Front_Stand,
    Diving_Intercept_Back_Stand,
    Diving_Intercept_Front_HandStand,
    Diving_Intercept_Back_HandStand,
    MiddleRopeGroggy_InRing,
    Front_CollarAndElbow,
    Rear_CollarAndElbow,
    Rear_WaistLock,
    Front_CornerChain_Tag,
    Rear_CornerChain_Tag,
    RopeChain_Tag,
    Ring_To_Apron_Tag,
    Rear_Apron_To_Ring_Tag,
    EFinisher_MAX UMETA(Hidden),
};

