#pragma once
#include "CoreMinimal.h"
#include "EELAchievementList.generated.h"

UENUM(BlueprintType)
enum class EELAchievementList : uint8 {
    AC_All_Trophies_Earned,
    AC_First_Win,
    AC_Guardrail_Offensive,
    AC_Nice_Catch,
    AC_Smooth_Footwork,
    AC_Finisher_Thief,
    AC_DANGER_Contents_Under_Pressure,
    AC_KABOOM,
    AC_The_Path_to_Elite,
    AC_Welcome_to_the_Elite,
    AC_Livin_the_Wrestlers_Life,
    AC_Hall_of_Famer,
    AC_T_Shirt_Collector,
    AC_Food_Critic,
    AC_Train_to_the_Max,
    AC_Casual_Gamer,
    AC_Professional_Gamer,
    AC_Making_Their_Debut,
    AC_Arena_Architect,
    AC_Promising_New_Tag_Team,
    AC_Decorator,
    AC_Belt_Taker,
    AC_Net_Shopper,
    AC_Big_Earner,
    AC_Full_Course,
    AC_Dont_Even_Need_My_Hands,
    AC_Dexterous_Dervish,
    AC_4_Way_Dominator,
    AC_Ring_Cleaner,
    AC_Match_of_the_Year,
    AC_Adept_Flyer,
    AC_Fearless_Rocket,
    AC_Guard_Crusher,
    AC_Rope_Wizard,
    AC_Corner_Wizard,
    AC_Equal_Opportunity_Player,
    AC_No_Feat_Too_Large,
    AC_All_Shall_Cower_Before_Me,
    AC_Table_Demolisher,
    AC_Beat_the_Best,
    AC_The_King_of_Harts,
    AC_Triple_Crown,
    AC_Watch_Your_Step,
    AC_None,
    AC_MAX UMETA(Hidden),
};

