#pragma once
#include "CoreMinimal.h"
#include "EELDebugMatchType.generated.h"

UENUM(BlueprintType)
enum class EELDebugMatchType : uint8 {
    DEBUG_MATCH_RULE_SINGLE_ALLPLAYER,
    DEBUG_MATCH_RULE_SINGLE_1PVSCOM,
    DEBUG_MATCH_RULE_TAG_ALLPLAYER,
    DEBUG_MATCH_RULE_TAG_1PVSCOM,
    DEBUG_MATCH_RULE_3WAY_ALLPLAYER,
    DEBUG_MATCH_RULE_3WAY_1PVSCOM,
    DEBUG_CASINO_BATTLE_ROYAL_TYPE_A_ALLPLAYER,
    DEBUG_CASINO_BATTLE_ROYAL_TYPE_A_1PVSCOM,
    DEBUG_CASINO_BATTLE_ROYAL_TYPE_B_1PVSCOM,
    DEBUG_MATCH_RULE_EXPLODING,
    DEBUG_MATCH_RULE_LIGHTS_OUT,
    DEBUG_MATCH_RULE_FALLS_COUNT_ANYWHERE,
    DEBUG_MATCH_RULE_4WAY_ALLPLAYER,
};

