#pragma once
#include "CoreMinimal.h"
#include "EELEntranceNameplateCommentConditionType.generated.h"

UENUM(BlueprintType)
enum class EELEntranceNameplateCommentConditionType : uint8 {
    Always,
    WrestlerID,
    Birthday,
    TeamName,
    Streak,
    LastEntry,
    EntryCount,
    WithManager,
    TitleHolder,
    TitleDefendDays,
    BattleRoyalWinner,
    CAWHeight,
    CAWWeight,
    TagTeamID,
    Skill_Momentum,
    Skill_FinisherSlot,
    Skill_SignatureSlot,
    Skill_ChainWrestling,
    Skill_ArmPower,
    Skill_KickPower,
    Skill_GrapplePower,
    Skill_DivingPower,
    Skill_SpringboardPower,
    Skill_MovementSpeed,
    ActionSkill,
    PassiveSkill,
    AIType,
    StreakForOnline,
    LastEntryForOnline,
    EntryCountForOnline,
    MatchScoreAverage,
    MatchScoreMax,
    CreateCAW,
    CreateCAA,
    RareItem,
    CareerClear,
    FavoriteWrestler,
    FavoriteArena,
    FavoriteWeapon,
    TableCrush,
    WeaponAttach,
    DropOnThumbtacks,
    WasDroppedOnThumbtacks,
    Explosion,
    Eliminate,
};

