#pragma once
#include "CoreMinimal.h"
#include "EPassiveSkillTriggerType.generated.h"

UENUM(BlueprintType)
enum class EPassiveSkillTriggerType : uint8 {
    All,
    ReceiveFinisher,
    Submission,
    ReceiveSubmission,
    Down,
    RopeReboundAttack,
    OutsideAttack,
    GuardSuccess,
    ReceiveSlam,
    ArmDamage,
    LegDamage,
    WeaponDamage,
    DirtyDamage,
    ReceiveFinisherPinOrSubmission,
    FirstChainWrestling,
    FirstAttack,
    GrapplePush,
    CornerWhipAttack,
    Tope,
    Diving,
    Springboard,
    EnvironmentAttack,
    PinKickout,
    ReceivePinKickout,
    TenMoves,
    Taunt,
    JumpingTouch,
    TwoPlatoon,
    EquipWeapon,
    BattleRoyaleBeat,
    BattleRoyale5Min,
    Explision,
    ReceiveExplision,
    ExplidingMatchRemain30sec,
    ReceiveInjury,
    TargetInjury,
    ReceiveBlood,
    TargetBlood,
    ReceiveFinalPin,
    ReceiveFinalSubmission,
    PinDexterity,
    HitPointZero,
    TargetSpecial,
    Finisher,
    ArmLegSubmission,
    Towplatoon,
};

