#pragma once
#include "CoreMinimal.h"
#include "ERA_Slot_TeamName.generated.h"

UENUM(BlueprintType)
enum class ERA_Slot_TeamName : uint8 {
    RA_TN_NONE,
    RA_TN_BEST_FRIENDS,
    RA_TN_THE_DARK_ORDER,
    RA_TN_DEATH_TRIANGLE,
    RA_TN_THE_ELITE,
    RA_TN_THE_INNER_CIRCLE,
    RA_TN_JURASSIC_EXPRESS,
    RA_TN_LUCHA_BROS,
    RA_TN_SCU,
    RA_TN_THE_YOUNG_BUCKS,
    RA_TN_TEAM_TAZ,
    RA_TN_THE_ACCLAIMED,
    RA_TN_TOP_FLIGHT,
    RA_TN_THE_GUNN_CLUB,
    RA_TN_THE_BUTCHER_N_THE_BLADE,
    RA_TN_PROUD_N_POWERFUL,
    RA_TN_NIGHTMARE_FAMILY,
    RA_TN_NATURAL_NIGHTMARES,
    RA_TN_PRIVATE_PARTY,
    RA_TN_CHAOS_PROJECT,
    RA_TN_THE_HYBRID2,
    RA_TN_FTR,
    RA_TN_THE_BROTHERHOOD,
    RA_TN_VARSITY_BLONDES,
};

